name: invidious
version: 1.21.0+4059
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  after_layout: 1.2.0
  audio_service: 0.18.13
  audio_session: 0.1.19
  auto_route: 8.1.3
  awesome_notifications: any
  awesome_notifications_core: 0.9.3
  back_button_interceptor: 7.0.3
  bloc: 8.1.4
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
  copy_with_extension: 5.0.4
  cronet_http: 1.3.2
  device_info_plus: 10.1.0
  dio: 5.4.3+1
  dynamic_color: 1.7.0
  easy_debounce: 2.0.3
  feedback: 3.1.0
  flutter_animate: 4.5.0
  flutter_bloc: 8.1.5
  flutter_displaymode: 0.6.0
  flutter_fadein: 2.0.0
  flutter_linkify: 6.0.0
  flutter_native_splash: 2.4.0
  flutter_svg: 2.0.10+1
  flutter_swipe_action_cell: 3.1.3
  flutter_web_auth: 0.5.0
  freezed_annotation: 2.4.1
  gap: 3.0.1
  http: 1.2.1
  intl: 0.19.0
  json_annotation: 4.9.0
  just_audio: 0.9.38
  logging: 1.2.0
  package_info_plus: 8.0.0
  path: any
  path_provider: 2.1.3
  receive_sharing_intent: 1.8.0
  sembast: 3.7.1
  sembast_sqflite: 2.2.0
  settings_ui: 2.0.2
  share_plus: 9.0.0
  sqflite: 2.3.3+1
  url_launcher: 6.2.6
  uuid: 4.4.0
  wakelock_plus: 1.2.5
  workmanager: 0.5.2
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  locale_names: 
    git: 
      url: https://github.com/lamarios/locale_names.git
      ref: master
  river_player: 
    git: 
      url: https://github.com/lamarios/river_player.git
      ref: master
  simple_pip_mode: 
    git: 
      url: https://github.com/song011794/simple_pip_mode_flutter.git
      ref: main
dev_dependencies: 
  auto_route_generator: any
  build_runner: ^2.4.10
  copy_with_extension_gen: 5.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  freezed: ^2.5.3
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  nock: 1.2.3
  pubspec_dependency_sorter: ^1.0.4
  test: any
  flutter_driver: 
    sdk: flutter
  flutter_test: 
    sdk: flutter
dependency_overrides: 
 # cupertino_icons: ^1.0.2
 # js: 0.7.1
  meta: 1.14.0
 # web: 0.5.0
flutter: 
  assets: 
    - assets/icon.svg
  uses-material-design: true
  generate: true
flutter_launcher_icons: 
  image_path: assets/icon-with-background.png
  android: 
    adaptive_icon_background: '#1D1B1E'
    adaptive_icon_foreground: assets/icon.png
    generate: true
  ios: false
  min_sdk_android: 21
